name = "evedata-docs"
compatibility_date = "2025-04-01"
preview_urls = true

[env.production]
route = { pattern = "docs.evedata.io", custom_domain = true }

[env.staging]
name = "evedata-docs-staging"
route = { pattern = "docs.evedata.dev", custom_domain = true }

[assets]
directory = "./site"
not_found_handling = "404-page"
