name: Publish
on:
  push:
    branches:
      - main
      - production
  pull_request:
    branches:
      - main
      - production

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            docs
            includes
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ (github.event_name == 'pull_request' || github.ref_name == 'main') && secrets.CLOUDFLARE_ACCOUNT_ID_DQT || secrets.CLOUDFLARE_ACCOUNT_ID_PRD }}
